# Generated by Django 6.0.3 on 2026-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='text', max_length=10),
        ),
    ]
