# Generated by Django 6.0.3 on 2026-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_message_audio_message_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
